### ISSUE TITLE
Rocket League v1.68 replays

### ISSUE THREAD

**Issue by Sciguymjm** [tfausak/rattletrap#145]
https://github.com/Bakkes/CPPRP/commit/9f583730dae37df66658abe71563d75fd37c8055

[1d167f3c-3648-416f-b14d-310a08707661.replay.zip](https://github.com/tfausak/rattletrap/files/3725877/1d167f3c-3648-416f-b14d-310a08707661.replay.zip)
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 43, in analyze_replay_file
    _json = decompile_replay(replay_path, output_path=output_path, overwrite=overwrite, rattletrap_path=rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 25, in decompile_replay
    return run_rattletrap.decompile_replay(replay_path, output_path, overwrite, rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 84, in decompile_replay
    return run_rattletrap_command(command, output_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 57, in run_rattletrap_command
    raise RattleTrapException(err_msg)
carball.rattletrap.run_rattletrap.RattleTrapException: b'rattletrap-linux: user error (don\'t know how to get attribute value Str {strValue = "TAGame.VehiclePickup_TA:NewReplicatedPickupData"})'. Code: 1
```

**Comment by Sciguymjm** [comment]
Fixed in #146
