### ISSUE TITLE
Issue with anniversary replays?

### ISSUE THREAD

**Issue by dtracers** [tfausak/rattletrap#147]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 43, in analyze_replay_file
    _json = decompile_replay(replay_path, output_path=output_path, overwrite=overwrite, rattletrap_path=rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 25, in decompile_replay
    return run_rattletrap.decompile_replay(replay_path, output_path, overwrite, rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 84, in decompile_replay
    return run_rattletrap_command(command, output_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 57, in run_rattletrap_command
    raise RattleTrapException(err_msg)
carball.rattletrap.run_rattletrap.RattleTrapException: b'rattletrap-linux: user error (could not get class name for object Str {strValue = "Archetypes.Ball.Ball_Anniversary"})'. Code: 1
```

https://cdn.discordapp.com/attachments/493849514680254468/633509409267384332/rattle_trap_error_anniversary.replay

**Comment by tfausak** [comment]
Seems like this should be an easy fix: https://github.com/jjbott/RocketLeagueReplayParser/commit/34b2c72fddd24d21c2aa8c5a2e1ac9f85942306c

**Comment by tfausak** [comment]
Re-uploading for posterity:
[rattle_trap_error_anniversary.zip](https://github.com/tfausak/rattletrap/files/3741505/rattle_trap_error_anniversary.zip)
