### ISSUE TITLE
Issue parsing replay, unkown property

### ISSUE THREAD

**Issue by dtracers** [tfausak/rattletrap#148]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 43, in analyze_replay_file
    _json = decompile_replay(replay_path, output_path=output_path, overwrite=overwrite, rattletrap_path=rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 25, in decompile_replay
    return run_rattletrap.decompile_replay(replay_path, output_path, overwrite, rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 84, in decompile_replay
    return run_rattletrap_command(command, output_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 57, in run_rattletrap_command
    raise RattleTrapException(err_msg)
carball.rattletrap.run_rattletrap.RattleTrapException: b'rattletrap-linux: user error (don\'t know how to read property value Str {strValue = "\\NUL\\NUL\\NUL\\NUL\\151\\163\\158\\n"})'. Code: 1
```

https://cdn.discordapp.com/attachments/493849514680254468/633510159779364865/rattle_trap_error_property.replay

**Comment by jjbott** [comment]
This replay is super jacked up. It's only 3k, and is missing almost all data. Not sure how RL is even showing its info

**Comment by dtracers** [comment]
There is more than one that we have that is like this too.

Maybe it is an autosave of a forfiet?

**Comment by tfausak** [comment]
Re-uploading for posterity:
[rattle_trap_error_property.zip](https://github.com/tfausak/rattletrap/files/3741506/rattle_trap_error_property.zip)

**Comment by Sciguymjm** [comment]
[8a5d4a0b-777a-4e36-8001-7c41b6a9a8e5.zip](https://github.com/tfausak/rattletrap/files/3741722/8a5d4a0b-777a-4e36-8001-7c41b6a9a8e5.zip)

Another one. Looks to be similar. Likely an upload from when a game doesn't start (not everyone connects but BMod still uploads)

**Comment by tfausak** [comment]
I'm also curious how Rocket League manages to show any information at all for these replays. That being said, since Rocket League won't actually load them, I'm not going to bother making Rattletrap handle them.
