### ISSUE TITLE
Issue parsing replay with weird ball

### ISSUE THREAD

**Issue by dtracers** [tfausak/rattletrap#149]
```
Traceback (most recent call last):
  File "/user_code/main.py", line 105, in parse_replay
    game_manager, proto_location, pandas_location = decompile_replay(replay_location)
  File "/user_code/main.py", line 41, in decompile_replay
    proto_manager = analyze_replay_file(filename, rattletrap_path=dir_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 43, in analyze_replay_file
    _json = decompile_replay(replay_path, output_path=output_path, overwrite=overwrite, rattletrap_path=rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/decompile_replays.py", line 25, in decompile_replay
    return run_rattletrap.decompile_replay(replay_path, output_path, overwrite, rattletrap_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 84, in decompile_replay
    return run_rattletrap_command(command, output_path)
  File "/env/local/lib/python3.7/site-packages/carball/rattletrap/run_rattletrap.py", line 57, in run_rattletrap_command
    raise RattleTrapException(err_msg)
carball.rattletrap.run_rattletrap.RattleTrapException: b'rattletrap-linux: user error (don\'t know how to get attribute value Str {strValue = "TAGame.Ball_TA:ReplicatedPhysMatOverride"})'. Code: 1
```

https://cdn.discordapp.com/attachments/493849514680254468/633510709346566164/rattle_trap_error_odd_ball.replay

**Comment by tfausak** [comment]
Re-uploading for posterity:
[rattle_trap_error_odd_ball.zip](https://github.com/tfausak/rattletrap/files/3741508/rattle_trap_error_odd_ball.zip)

**Comment by Sciguymjm** [comment]
[8a5d4a0b-777a-4e36-8001-7c41b6a9a8e5.zip](https://github.com/tfausak/rattletrap/files/3741721/8a5d4a0b-777a-4e36-8001-7c41b6a9a8e5.zip)

Another one. Looks to be similar.

**Comment by tfausak** [comment]
Prior art:
https://github.com/jjbott/RocketLeagueReplayParser/commit/d36389950999e93a07f45ebdcffb70ab9e0789d1
https://github.com/cubeee/replay-kt/commit/94eb79f1629bb85aa9d66540091c4eea52dcc406
